baseURL: "https://sophiamo.github.io"
title: Sophia Mo
paginate: 20
theme: PaperMod

enableGitInfo: true
ignoreErrors:

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv.pdf
          weight: 1
        - name: Job Market Paper
          url: Mo_JMP.pdf
          weight: 2
        - name: Research
          url: papers/
          weight: 3

params:
    description: "I am a PhD candidate in Economics at Harvard University. My research fields are macroeconomics and labor economics."
    author: Sophia Mo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    social:
      twitter: sophiaymo
    profileMode:
          enabled: true
          title: Sophia Mo
          subtitle:
              I hold a Ph.D. in Economics from Harvard University, where my research bridged labor economics and applied macroeconomics. My work examines how informal coworker networks shape job-search beliefs, referral, and mobility across firms and sectors. Using matched employer–employee data, survey, and structural modeling, I identify the causal channels through which social capital drives worker mobility,
              and quantify how these networks influence welfare and the propagation of economic shocks. <br><br>
              Prior to my doctoral studies, I was a Research Professional at The University of Chicago Booth School of Business. I completed my B.S. in Mathematics and my B.A. in Economics and Political Science at the University of Chicago. <br><br>
              You can reach me at yiningmo@fas.harvard.edu <br><br>
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Sophia Mo
          buttons:
            - name: CV
              url: cv.pdf
            - name: Job Market Paper
              url: Mo_JMP.pdf
            - name: Research
              url: papers/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:yiningmo@fas.harvard.edu
        - name: Twitter
          url: https://x.com/sophiaymo
        - name: Bluesky
          url: https://sophiaymo.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sophia Mo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

module:
  imports:
    - path: github.com/SophiaMo/hugo-seo
